/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package supermarket.billing.system;

import java.sql.*;
import javax.swing.JOptionPane;
//import java.sql.DriverManager;

/**
 *
 * @author pritesh jung karki
 */
public class AdminTask extends javax.swing.JFrame {

    /**
     * Creates new form AdminTask
     */
    public AdminTask() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Cashierbutton_jButton1 = new javax.swing.JButton();
        Appicon_jLabel2 = new javax.swing.JLabel();
        Stockbutton_jButton3 = new javax.swing.JButton();
        Salesbutton_jButton4 = new javax.swing.JButton();
        Exitbutton_jButton5 = new javax.swing.JButton();
        Mainlabel_jLabel1 = new javax.swing.JLabel();
        jDesktopPane1 = new javax.swing.JDesktopPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Cashierbutton_jButton1.setBackground(new java.awt.Color(204, 204, 204));
        Cashierbutton_jButton1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Cashierbutton_jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cashiericon.png"))); // NOI18N
        Cashierbutton_jButton1.setText("Cashier");
        Cashierbutton_jButton1.setBorder(null);
        Cashierbutton_jButton1.setContentAreaFilled(false);
        Cashierbutton_jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cashierbutton_jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(Cashierbutton_jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, 130, 30));

        Appicon_jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/imageedit_1_7245834402.jpg"))); // NOI18N
        Appicon_jLabel2.setText("jLabel2");
        getContentPane().add(Appicon_jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 160, 40));

        Stockbutton_jButton3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Stockbutton_jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/stockbox.png"))); // NOI18N
        Stockbutton_jButton3.setText("Stock");
        Stockbutton_jButton3.setContentAreaFilled(false);
        Stockbutton_jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Stockbutton_jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(Stockbutton_jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 20, 110, 30));

        Salesbutton_jButton4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Salesbutton_jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/imageedit_6_8446667857.jpg"))); // NOI18N
        Salesbutton_jButton4.setText("Sales");
        Salesbutton_jButton4.setContentAreaFilled(false);
        Salesbutton_jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Salesbutton_jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(Salesbutton_jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 20, 100, 30));

        Exitbutton_jButton5.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        Exitbutton_jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/exit.jpg"))); // NOI18N
        Exitbutton_jButton5.setContentAreaFilled(false);
        Exitbutton_jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Exitbutton_jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(Exitbutton_jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 20, 140, 30));

        Mainlabel_jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bk.jpg"))); // NOI18N
        getContentPane().add(Mainlabel_jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1060, 80));

        jDesktopPane1.setBackground(new java.awt.Color(0, 153, 153));

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1060, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 480, Short.MAX_VALUE)
        );

        getContentPane().add(jDesktopPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 1060, 480));

        pack();
    }// </editor-fold>//GEN-END:initComponents

   
    private void Cashierbutton_jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cashierbutton_jButton1ActionPerformed
        // TODO add your handling code here:
        CashierDetails cd = new CashierDetails();
        this.jDesktopPane1.add(cd);
        cd.setVisible(true);

    }//GEN-LAST:event_Cashierbutton_jButton1ActionPerformed

    private void Stockbutton_jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Stockbutton_jButton3ActionPerformed
        UpdateStock us = new UpdateStock();
        this.jDesktopPane1.add(us);
        us.setVisible(true);
    }//GEN-LAST:event_Stockbutton_jButton3ActionPerformed

    private void Exitbutton_jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Exitbutton_jButton5ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        LoginFrame lf = new LoginFrame();
        lf.setVisible(true);
        
    }//GEN-LAST:event_Exitbutton_jButton5ActionPerformed

    private void Salesbutton_jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Salesbutton_jButton4ActionPerformed
       SalesPerDay spd = new SalesPerDay();
       this.jDesktopPane1.add(spd);
       spd.setVisible(true);
    }//GEN-LAST:event_Salesbutton_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminTask.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminTask.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminTask.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminTask.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminTask().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Appicon_jLabel2;
    private javax.swing.JButton Cashierbutton_jButton1;
    private javax.swing.JButton Exitbutton_jButton5;
    private javax.swing.JLabel Mainlabel_jLabel1;
    private javax.swing.JButton Salesbutton_jButton4;
    private javax.swing.JButton Stockbutton_jButton3;
    private javax.swing.JDesktopPane jDesktopPane1;
    // End of variables declaration//GEN-END:variables
}
