/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package supermarket.billing.system;

/**
 *
 * @author pritesh jung karki
 */
public class CashierTask extends javax.swing.JFrame {

    /**
     * Creates new form CashierTask
     */
    public CashierTask() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Quickbillimage_jLabel2 = new javax.swing.JLabel();
        Create_bill = new javax.swing.JButton();
        Search_bill = new javax.swing.JButton();
        Product_info = new javax.swing.JButton();
        Sales = new javax.swing.JButton();
        Exit = new javax.swing.JButton();
        MainFrame_jLabel1 = new javax.swing.JLabel();
        jDesktopPane1 = new javax.swing.JDesktopPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1065, 635));
        setSize(new java.awt.Dimension(1065, 635));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Quickbillimage_jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/imageedit_1_7245834402.jpg"))); // NOI18N
        getContentPane().add(Quickbillimage_jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 160, 40));

        Create_bill.setBackground(new java.awt.Color(204, 204, 204));
        Create_bill.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Create_bill.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/createbillimage.jpg"))); // NOI18N
        Create_bill.setText("Create Bill");
        Create_bill.setBorder(null);
        Create_bill.setContentAreaFilled(false);
        Create_bill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Create_billActionPerformed(evt);
            }
        });
        getContentPane().add(Create_bill, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 20, 130, -1));

        Search_bill.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Search_bill.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/searchicon.png"))); // NOI18N
        Search_bill.setText("Search Bill");
        Search_bill.setBorderPainted(false);
        Search_bill.setContentAreaFilled(false);
        Search_bill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Search_billActionPerformed(evt);
            }
        });
        getContentPane().add(Search_bill, new org.netbeans.lib.awtextra.AbsoluteConstraints(353, 20, 150, -1));

        Product_info.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Product_info.setText("Product Information");
        Product_info.setBorderPainted(false);
        Product_info.setContentAreaFilled(false);
        Product_info.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Product_infoActionPerformed(evt);
            }
        });
        getContentPane().add(Product_info, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 30, 160, -1));

        Sales.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Sales.setText("Sales");
        Sales.setBorderPainted(false);
        Sales.setContentAreaFilled(false);
        Sales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalesActionPerformed(evt);
            }
        });
        getContentPane().add(Sales, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 30, -1, -1));

        Exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/exit.jpg"))); // NOI18N
        Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitActionPerformed(evt);
            }
        });
        getContentPane().add(Exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 20, 150, -1));

        MainFrame_jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bk.jpg"))); // NOI18N
        getContentPane().add(MainFrame_jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1060, 75));

        jDesktopPane1.setBackground(new java.awt.Color(0, 153, 153));
        jDesktopPane1.setPreferredSize(new java.awt.Dimension(1050, 513));

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1050, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 513, Short.MAX_VALUE)
        );

        getContentPane().add(jDesktopPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 1050, 513));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Product_infoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Product_infoActionPerformed
       ProInformation pro=new ProInformation();
        this.jDesktopPane1.add(pro);
        pro.setVisible(true);
    }//GEN-LAST:event_Product_infoActionPerformed

    private void ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitActionPerformed
        LoginFrame lf = new LoginFrame();
        lf.setVisible(true);
        this.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_ExitActionPerformed

    private void Create_billActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Create_billActionPerformed
        CreateBill bill=new CreateBill();
        this.jDesktopPane1.add(bill);
        bill.setVisible(true); 
        // TODO add your handling code here:
    }//GEN-LAST:event_Create_billActionPerformed

    private void Search_billActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Search_billActionPerformed
        SearchBill bil1=new SearchBill();
        this.jDesktopPane1.add(bil1);
        bil1.setVisible(true);        // TODO add your handling code here:

        // TODO add your handling code here:
    }//GEN-LAST:event_Search_billActionPerformed

    private void SalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalesActionPerformed
        SalesPerDay spd = new SalesPerDay();
        this.jDesktopPane1.add(spd);
        spd.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_SalesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CashierTask.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CashierTask.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CashierTask.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CashierTask.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CashierTask().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Create_bill;
    private javax.swing.JButton Exit;
    private javax.swing.JLabel MainFrame_jLabel1;
    private javax.swing.JButton Product_info;
    private javax.swing.JLabel Quickbillimage_jLabel2;
    private javax.swing.JButton Sales;
    private javax.swing.JButton Search_bill;
    private javax.swing.JDesktopPane jDesktopPane1;
    // End of variables declaration//GEN-END:variables
}
